import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const iranSans = localFont({
  src: [
    {
      path: "./fonts/irsansb.ttf",
      weight: "900",
      style: "normal",
    },

    {
      path: "./fonts/irsans.ttf",
      weight: "400",
      style: "normal",
    },
  ],
  variable: "--font-iran-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" dir="rtl">
      <body
        className={`${iranSans.variable} antialiased container max-w-[1700px] mx-auto overflow-x-hidden bg-pink-400 bg-opacity-80`}
      >
        <main>
          <Header />
          {children}
          <Footer />
        </main>
      </body>
    </html>
  );
}
